
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-score-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-score-scheduler
  template:
    metadata:
      labels:
        app: controller-score-scheduler
    spec:
      nodeSelector:
          node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      serviceAccountName: controller-score-scheduler
      containers:
        - name: kube-scheduler
          image: alibeiti/kube-scheduler-controller-score:3
          command:
            - "/bin/kube-scheduler"
            - "--config=/etc/kube-scheduler/scheduler-config.yaml"
            - "-v=4"
          volumeMounts:
            - name: config
              mountPath: /etc/kube-scheduler
      volumes:
        - name: config
          configMap:
            name: controller-score-scheduler-config