apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration


#clientConnection:
#  kubeconfig: "/etc/kubernetes/scheduler.conf"

# 2) Leader election settings so only 1 scheduler is active.
leaderElection:
  leaderElect: true
  resourceName: "controller-score-scheduler-lock"
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s

profiles:
  - schedulerName: controller-score-scheduler

    #Plugins: disable all built-in filtering/scoring,
    #hen enable only ControllerScore.
    plugins:
      filter:
        enabled:
          - name: "TaintToleration"
          - name: "ControllerScore"
        disabled:
          - name: "*"
      score:
        enabled:
          - name: "ControllerScore"
            weight: 1
        disabled:
          - name: "*"

    #pluginConfig: pass custom args to ControllerScore
    pluginConfig:
      - name: "ControllerScore"
        args:
          port: 6000
          path: "/getScore"
          timeoutMillis: 200
